### PR TITLE
Update libsyntax api to work with nightly 1.38

### LINKED ISSUE #256: method `emit_fatal_errors` is private
Fresh rust, fresh cargo-src, doesn't work:

```
   cargo install cargo-src
   ...
   Compiling want v0.0.4
   Compiling rustdoc-highlight v0.1.7
   Compiling syn v0.11.11
error[E0624]: method `emit_fatal_errors` is private
   --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdoc-highlight-0.1.7/src/lib.rs:200:32
    |
200 |                     self.lexer.emit_fatal_errors();
    |                                ^^^^^^^^^^^^^^^^^

error[E0616]: field `sess` of struct `syntax::parse::lexer::StringReader` is private
   --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdoc-highlight-0.1.7/src/lib.rs:201:21
    |
201 |                     self.lexer.sess.span_diagnostic
    |                     ^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0616, E0624.
For more information about an error, try `rustc --explain E0616`.
error: Could not compile `rustdoc-highlight`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-src v0.1.6`, intermediate artifacts can be found at `/tmp/cargo-installvSQWyx`

Caused by:
  build failed
rust@desk:~$ rustc --version
rustc 1.36.0-nightly (a784a8022 2019-05-09)
rust@desk:~$ 

```

Would be nice if you provided the executable for Ubuntu x86_64 in Releases section, as compiling from sources or installing doesnt work.

### PR DESCRIPTION
**Pull request by dpmkl**
Updated so it works with Rust nightly 1.38.
This depends on a pull request for rustdoc-highlight. 
https://github.com/nrc/rustdoc-highlight/pull/9
This fixes #256

### CODE REVIEW

**Comment by nrc** [comment]
Thanks!

**Comment by jhpratt** [comment]
@nrc Any plans to push this in a new version? Install is currently failing on newer compilers.

**Comment by nrc** [comment]
Published 0.1.7. Sorry it took so long, it was non-trivial due to a complex rustdoc-highlight update.
